name = "tic-tac-toe-ai"
main = "src/index.ts"
compatibility_date = "2024-08-19"
keep_vars = true

[vars]
ENVIRONMENT = "development"

[env.production]
[env.production.vars]
ENVIRONMENT = "production"
