name: Deploy Worker to Cloudflare
on:
  push:
    branches:
      - main

env:
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CF_TOKEN }}

jobs:
  deploy:
    name: Deploy Main
    # only if merged to main
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./worker
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Deploy
        run: npm run deploy
